name	atomicnumber	Symbol	Group	electronarr	reactivity	RAM
INSERT INTO element VALUES( NULL,'Gallium',	31,	'Ga',	3,	'2.8.8.3'	,'high',	70);
INSERT INTO element VALUES( NULL, 'Indium',	49	,'In',3, '0' ,	'high',	115);
INSERT INTO element VALUES( NULL, 'Thallium',	81,	'Ti',	3,	'0' ,	'high',	204);
INSERT INTO element VALUES( NULL,'Ununtrium',	113	'Uut'	3	'0'	,'high',	0);
INSERT INTO element VALUES( NULL,'Carbon',	6	,'C',	4,	'2.4'	,'low',	12);
INSERT INTO element VALUES( NULL, 'Silicon'	,14	,'Si'	,4	'2.8.4'	,'low',	28);
INSERT INTO element VALUES( NULL,'Germanium',	32	,'Ge'	,4	'0'	,'low',	1);
INSERT INTO element VALUES( NULL,'Tin',	50,	'Sn',	4,	'0'	,'low',	119);
INSERT INTO element VALUES( NULL,'Lead'	82	'Pb'	4	'0'	,'low',	207);
INSERT INTO element VALUES( NULL,'Flevorium',	114	,'Fl',	4	,'0',	,'low',	289);
INSERT INTO element VALUES( NULL,'Nitrogen'	7	,'N',	5,	'2.5'	,'high',14);
INSERT INTO element VALUES( NULL,'Phosphorus',	15,	'P',	5	,'2.8.5'	,'high',	31);
INSERT INTO element VALUES( NULL,'Arsenic',	33,	'As',	5,	'0'	,'high',	75);
INSERT INTO element VALUES( NULL,'Antimony'	,51	, 'Sb'	,5,	'0'	,'high',	122);
INSERT INTO element VALUES( NULL,'Bismuth',	83,	'Bi',	5,	'0'	,'high',	209);
INSERT INTO element VALUES( NULL,'Ununpentium',	115,	'Uup'	,5	,'0'	,'high',	0);
INSERT INTO element VALUES( NULL,'Oxygen',	8,	'O'	,6	,'2.6'	,'high',	16);
INSERT INTO element VALUES( NULL,'Sulphur'	,16	,'S'	,6	,'2.8.6'	,'high',	32);
INSERT INTO element VALUES( NULL,'Selenium',	34,	'Se'	,6	,'0'	,'high',	79);
INSERT INTO element VALUES( NULL,'Tellurium',	52	,'Te'	,6	,'0'	,'high',	128 );
INSERT INTO element VALUES( NULL,'Polonium',	84	,'Po'	,6	,'0',	,'high',	209);
INSERT INTO element VALUES( NULL,'Livermorium',	116	,'Lv'	,6	,'0',	,'high',	0);
INSERT INTO element VALUES( NULL,'Fluorine',	9,	'F'	,7,	'2.7'	,'high',	14);
INSERT INTO element VALUES( NULL,'Chlorine'	,17,	'Cl'	,7	,'2.8.7'	,'high',	35);
INSERT INTO element VALUES( NULL,'Bromine',	35	,'Br'	,7	,'0'	,,'high',	80);
INSERT INTO element VALUES( NULL,'Iodine',	53	,'I'	,7,	'0'	,'high',	127);
INSERT INTO element VALUES( NULL,'Astatine',	85,	'At',	7	,'0'	,'high',	210);
INSERT INTO element VALUES( NULL,'Ununseptium',	117,	'Uus',	7,	'0'	,'high',	0);
INSERT INTO element VALUES( NULL,'Hellium',	2,	'He'	,8,	'2',	,'high',	4);
INSERT INTO element VALUES( NULL,'Neon',	10,	'Ne',	8	,'2.8'	,'high',	20);
INSERT INTO element VALUES( NULL,'Argon',	18,	'Ar'	,8	,'2.8.8'	,'high',	40);
INSERT INTO element VALUES( NULL,'Krypton',	36	,'Kr',	8,	'0'	,'high',	84);
INSERT INTO element VALUES( NULL,'Xenon',	54,	'Xe',	8	,'0',	,'high',	131);
INSERT INTO element VALUES( NULL,'Radon',	86,	'Rn'	,8,	'0'	,'high',	222);
INSERT INTO element VALUES( NULL,'Ununoctium',	118,	'Uuo',	8,	'0'	,'high',	0);
INSERT INTO element VALUES( NULL,'Iron',	26,	'Fe'	,'Transition'	,'0'	,'high',	56);